AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda function for Print Your Trip - RGB to CMYK image conversion

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 1024
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps
    LoggingConfig:
      LogFormat: JSON

Resources:
  PDFConversionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref SourceBucket
        - S3WritePolicy:
            BucketName: !Ref SourceBucket
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref SourceBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: -rgb.jpg
                  - Name: suffix
                    Value: -rgb.jpeg
                  - Name: suffix
                    Value: -rgb.png
                  - Name: suffix
                    Value: -rgb.gif
                  - Name: suffix
                    Value: -rgb.bmp
                  - Name: suffix
                    Value: -rgb.tiff
                  - Name: suffix
                    Value: -rgb.webp

  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-source-${AWS::Region}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PDFConversionFunction:
    Description: PDF Conversion Lambda Function ARN
    Value: !GetAtt PDFConversionFunction.Arn
  SourceBucketName:
    Description: Name of the source S3 bucket
    Value: !Ref SourceBucket
